### ISSUE TITLE
Module inputs rounding down decimal values

### ISSUE THREAD

**Issue by timplumb** [sruupl/batflat#31]
I've been looking at creating a simple module for BatFlat and have been struggling with this issue for the last day or so. If I add a decimal figure to a module input (20.99 for example) the figure is rounded down to the nearest integer (20 in this case). I thought this was an issue with my code but all of the standard modules in the CMS also do the same thing. For example if you add a gallery image caption 99.22 then you'll get just 99.
What inside BatFlat is causing this to happen?

**Comment by michu2k** [comment]
Hi
This issue happens, when PDO executes a new query, because of this: PDO::PARAM_INT. It's changing every number to int. This is a potential fix for this bug:

I'm not a PHP specialist, so @klocus take a look 😄 

inc/core/lin/QueryBuilder.php line 877
![bez nazwy-1](https://user-images.githubusercontent.com/22056149/46221378-342c0b80-c34d-11e8-98a4-88d9baae3332.jpg)

**Comment by timplumb** [comment]
Fantastic. That worked perfectly @michu2k. Many thanks.
How do I go about getting this issue logged or fixed in the core CMS?

**Comment by klocus** [comment]
You can change `QueryBuilder.php` like @michu2k said. Or you can add HTML tag to your number, ex. `<span>99.22</span>` ;-)
