### ISSUE TITLE
FTP/ Server config 

### ISSUE THREAD

**Issue by moamm** [sruupl/batflat#57]
Hi all, after using the CMS to create my site, i've gone to upload it to my host domain but only the index page shows up and everything else returns an error if i go to click on a new page or login. 

Its super weird because it works perfectly and is super fast when i was testing using MAMP. Ive also double checked my host requirements such as PHP and Apache and they are all the same as my localhost. Have i done something wrong? 

My hosting provider is go daddy and i'm using a mac.

Appreciate the help and love the product.

**Comment by michu2k** [comment]
Hi @moamm 
Please check the list below:
1. Does your server have the minimum requirements and all the important extensions are enabled (For more info check documentation - _Requirements_ & _Installation_ section)?
2. Does the problem is existing on clear Batflat installation?
3. Do your pages have selected proper `.html` template?
4. Does your custom template/module have any errors (enabled DEV_MODE required)?
5. Do your files have been uploaded correctly on your website (especially `.htaccess` file)?

**Comment by moamm** [comment]
@michu2k 

I think its my server, everything works fine using my local server.I tried uploading the batflat-master folder and the same thing was happening, just the home page was showing and every time i tried clicking a nav item or logging in, its like a page not found error: http://penknifedesign-studio.com/batflat-master/ (fresh master project so the password is admin).

My server is also up to date with apache and php and also allows sqlite. I haven't looked at changing the .htaccess file, do i need to change this at all?

**Comment by michu2k** [comment]
Please enable `DEV_MODE` (inc/core/defines.php) to check if there are errors on these pages.

**Comment by moamm** [comment]
ahh, you're right. It seems i am missing one php extension

**Comment by michu2k** [comment]
The problem seems to be resolved. If you have further questions or problems, please create a new issue.
